yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('index.html', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView, PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # создание нового пользователя
    path('signup/',
         views.SignUp.as_view(),
         name='signup'),
    # вход под своей учетной записью
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    # выход из учётной записи
    path('logout/',
         LogoutView.as_view
         (template_name='users/logged_out.html'),
         name='logout'),
    # восстановление пароля
    path('password_reset/',
         PasswordResetView.as_view
         (template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view
         (template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    # изменение пароля
    path('password_change/',
         PasswordChangeView.as_view
         (template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change_done/',
         PasswordChangeDoneView.as_view
         (template_name='users/password_change_done.html'),
         name='password_change_done'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include(('posts.urls'), namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include(('users.urls'), namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include(('about.urls'), namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'

yatube/templates/includes/comment.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media px-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
      <p>
        {{ comment.created }}
      </p>  
    </div>
  </div>
{% endfor %} 

yatube/templates/includes/footer.html
  <footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: lightskyblue">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      <button class="navbar-toggler me-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">        
      <div class="nav nav-pills me-auto"><!--nav-item-->  
        {% with request.resolver_match.view_name as view_name %}
          <a class="nav-link {% if view_name == 'about:author' %} active {%endif%}"
            href="{% url 'about:author' %}">Об авторе</a>
          <a class="nav-link {% if view_name == 'about:tech' %} active {%endif%}"
            href="{% url 'about:tech' %}">Технологии</a>
        {% if user.username %}
          <a class="nav-link {% if view_name == 'about:new' %} active {%endif%}"
            href="{% url 'posts:post_create' %}">Новая запись</a>
        {% endif %}  
      </div>
    </div>  
      <div class="navbar nav me-right"><!--nav-user-->
        {% if user.username %}   
        Пользователь: {{ user.username }}
        <a class="btn btn-link"
          href="{% url 'users:password_change' %}">Изменить пароль</a>
        <a class="btn btn-outline-danger" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="btn btn-link" href="{% url 'users:signup' %}">Регистрация</a>
        <a class="btn btn-outline-success" href="{% url 'users:login' %}">Войти</a>
        {% endif %}
        {% endwith %}   
      </div>
  </div> <!--container-->
</nav>      
   